version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15                    # Use PostgreSQL version 15
    container_name: fitness_agent_db      # Name for the container
    environment:
      POSTGRES_DB: fitness_agent          # Database name
      POSTGRES_USER: admin             # Username
      POSTGRES_PASSWORD: admin_password     # Password (change this!)
      POSTGRES_HOST_AUTH_METHOD: trust    # Allow connections (dev only)
    ports:
      - "5433:5432"                       # Map port 5433 (host) to 5432 (container)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
    restart: unless-stopped               # Auto-restart if it crashes

# Named volume to store database data
volumes:
  postgres_data: