version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15                    # Use PostgreSQL version 15
    container_name:      # Name for the container
    environment:
      POSTGRES_DB:          # Database name
      POSTGRES_USER:           # Username
      POSTGRES_PASSWORD:      # Password (change this!)
      POSTGRES_HOST_AUTH_METHOD: trust    # Allow connections (dev only)
    ports:
      - "5433:5432"                       # Map port 5433 (host) to 5432 (container)
    volumes:
      -   # Persist data
    restart: unless-stopped               # Auto-restart if it crashes
    networks:
      - 

# Named volumes and networks
volumes:
  postgres_data:

networks:
  fitness_network:
    driver: bridge
