"""describe your changes

Revision ID: a318dab79f4d
Revises: 030f09a6c59a
Create Date: 2025-10-09 19:28:06.375759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a318dab79f4d'
down_revision: Union[str, None] = '030f09a6c59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('activity_level', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('workout_days_per_week', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('workout_duration_minutes', sa.Integer(), nullable=True))
    op.drop_column('user_profiles', 'workout_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('workout_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'workout_duration_minutes')
    op.drop_column('user_profiles', 'workout_days_per_week')
    op.drop_column('user_profiles', 'activity_level')
    # ### end Alembic commands ###
