"""add health_metrics and tips to fitness_plans

Revision ID: b5e44d5d424a
Revises: a318dab79f4d
Create Date: 2025-10-17 14:03:22.639204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5e44d5d424a'
down_revision: Union[str, None] = 'a318dab79f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_plans', sa.Column('health_metrics', sa.JSON(), nullable=True))
    op.add_column('fitness_plans', sa.Column('tips', sa.JSON(), nullable=True))
    op.drop_column('fitness_plans', 'last_modified')
    op.drop_column('fitness_plans', 'status')
    op.drop_column('fitness_plans', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_plans', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fitness_plans', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fitness_plans', sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('fitness_plans', 'tips')
    op.drop_column('fitness_plans', 'health_metrics')
    # ### end Alembic commands ###
